### ISSUE TITLE
Add gitter api based authentication to the app

### ISSUE THREAD

**Issue by abishekvashok** [coding-blocks/Chatter#1]
- [x] Take out the current chat activity as it is a boiler plate only.
- [x] Create a new Gitter app in order to make use of the gitter api
- [x] Implement authentication as mentioned in a complex process by the Gitter API at: https://developer.gitter.im/docs/authentication
- [x] For the last phase a networking client can be used as the stock way sucks like OkHttp
- [x] Store the generated access code in shared preference and display it in dashboard activity.
- [x] When no access_code is there make the user to authenticate again and if internet is also absent in addition prompt the user to authenticate.
- [x] Add Butterknife

The steps are complex and would need the use of a Web browser thus recommending to use a WebView and a dedicated activity for authentication.

Complexity: Hard.

CC: @the-dagger @championswimmer @garg-anuj

**Comment by abishekvashok** [comment]
Working on it, if possible please add bounties.

**Comment by abishekvashok** [comment]
Please review #2

**Comment by abishekvashok** [comment]
Edited the issue to implement butterknife

**Comment by abishekvashok** [comment]
@the-dagger mind closing this and adding a bounty pls?

**Comment by the-dagger** [comment]
@championswimmer Please take a look. ^
