### ISSUE TITLE
add app screenshots to readme

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/Chatter#14]

**Comment by akshat14714** [comment]
@championswimmer is this issue still open? Can you help me how to start the app on my local system.

**Comment by akshat14714** [comment]
@abishekvashok can you please give me some more insight as to how to download and build?

**Comment by abishekvashok** [comment]
It's and android app, open it up on android studio and hit build.

**Comment by PrajwalM2212** [comment]
@championswimmer  I would like to do this .
