### ISSUE TITLE
Gradle build fails

### ISSUE THREAD

**Issue by abishekvashok** [coding-blocks/Chatter#140]
**Actual Behaviour**

Gradle build fails raising the exception that `compile` is depreciated.

**Expected Behaviour**

Gradle build should not fail.

**Steps to reproduce it**

Try to build the project on the latest Android studio version.

**Expected Bounty**

100

**Comment by abishekvashok** [comment]
@championswimmer @the-dagger solved in #142 please review and add a bounty!

**Comment by abishekvashok** [comment]
@the-dagger @championswimmmer I would appreciate a bounty on this :P

**Comment by the-dagger** [comment]
Done!
