### ISSUE TITLE
Add bottom navigation bar back

### ISSUE THREAD

**Issue by abishekvashok** [coding-blocks/Chatter#145]
**Actual Behaviour**

Bottom navigation bar was removed and the app currently uses a menu for navigation!
Currently when you open the dashboard activity, a full screen fragment is created which opens the RomsFragment. On click on any room, another activity is opened just to display a similar full screen fragment. Here fragments are not used correctly. The app uses a menu for navigation which is rotten old style.
The Android docs specify a fragment as:
> A Fragment represents a behavior or a portion of user interface in a FragmentActivity. You can combine multiple fragments in a single activity to build a multi-pane UI and reuse a fragment in multiple activities. You can think of a fragment as a modular section of an activity, which has its own lifecycle, receives its own input events, and which you can add or remove while the activity is running (sort of like a "sub activity" that you can reuse in different activities).

**Expected beviour**

Bottom navigation bar should be added. Code should be refractored such that all current functionalities of the app work, the fragments must be used inside a single activity and activity changes should be done only when necessary.

**What to do**
- [ ] Add bottom navigation bar
- [ ] Takeout hardcoded functions implemented in RoomActivity
- [ ] Implement the same functions with better logic in dashboard activity.
- [ ] Update adapter to call open Room Function passing only minimal arguments.
- [ ] Update code so that all other functionalities remain intact
- [ ] Takeout RoomActivity and it's menu.

**Expected Bounty**

2000

**Comment by aggarwalpulkit596** [comment]
there is no need to have a bottom navigation bar as there is only one fragment which is required.

**Comment by abishekvashok** [comment]
> there is no need to have a bottom navigation bar as there is only one fragment which is required.

Material design guidelines specifies it as the desired mode of navigation

**Comment by abishekvashok** [comment]
- [x] Add bottom navigation bar
- [x] Takeout hardcoded functions implemented in RoomActivity
- [x] Implement the same functions with better logic in dashboard activity.
- [x] Update adapter to call open Room Function passing only minimal arguments.
- [x] Update code so that all other functionalities remain intact
- [x] Takeout RoomActivity and it's menu.

Done in #149

**Comment by championswimmer** [comment]
I don't like this approach. A nav drawer is better
