### ISSUE TITLE
fix minification on release

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/Chatter#165]
currently enabling proguard on release fails to build. we need to fix this as releases must be minified

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya can you be little more specific about the error

**Comment by championswimmer** [comment]
try to enable minify and build, you'll see the errors.

**Comment by aggarwalpulkit596** [comment]
okayy :)

**Comment by championswimmer** [comment]
reduced to 500 because it was my mistake I thougt we are still using Realm
When using Realm, fixing proguard rules becomes really really hard.
