### ISSUE TITLE
Set up unit test and run them on travis/circleci

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/Chatter#180]

**Comment by aggarwalpulkit596** [comment]
@the-dagger @championswimmer please review

**Comment by championswimmer** [comment]
making code coverage target 50% a separate issue

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya can you tell what should include in unit tests :)

**Comment by championswimmer** [comment]
any simple thing. construct a class or something. just make sure the testing setup works in this issue. anything more than 1% coverage is ok to show that testing setup works.

add real tests for the other issue.

**Comment by aggarwalpulkit596** [comment]
Okay that's easy 😅

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya there was a lot of complication for clicking button i had to find individual xpath of buttons so i think 1000 was good enough :P 
P.S.I also need to change my github password 🔑 can you review this asap

**Comment by championswimmer** [comment]
okay changing it to 1000, but you need to add travis and circleci configs too

**Comment by championswimmer** [comment]
travis is only checking build, not checking tests right now. and circleci doesn't exist
