### ISSUE TITLE
Design an icon for the app

### ISSUE THREAD

**Issue by abishekvashok** [coding-blocks/Chatter#3]
An app icon would be awesome.

CC: @championswimmer @the-dagger

**Comment by abishekvashok** [comment]
Should we do this now?

**Comment by ArushiSinghal** [comment]
@abishekvashok I have selected some of the icons please review
![10](https://user-images.githubusercontent.com/20858804/27483855-a16cecca-5844-11e7-8af1-ad385c0cbd49.png)
![9](https://user-images.githubusercontent.com/20858804/27483860-a32ff354-5844-11e7-87d7-46050951d9e5.png)
![7](https://user-images.githubusercontent.com/20858804/27483863-a50fea6c-5844-11e7-8b0f-e13ea750e7ba.png)
<img width="512" alt="6" src="https://user-images.githubusercontent.com/20858804/27483865-a7a208a0-5844-11e7-993a-622ba7e6f311.png">

**Comment by the-dagger** [comment]
@ArushiSinghal 3rd and 4th icons look quite nice.
Can you use the colors used in gitter's UI instead for consistency?

https://gitter.im

**Comment by ArushiSinghal** [comment]
@the-dagger I have changed the colour. Please have a look
1)
![imageedit_5_3465423032](https://user-images.githubusercontent.com/20858804/27491032-51c6bcb8-585e-11e7-95b9-aef42f5874c8.png)
2)
![imageedit_3_4324297320](https://user-images.githubusercontent.com/20858804/27491037-55dc5d58-585e-11e7-8a36-cc5f7fbc2b0a.png)
3)
![imageedit_2_8413654096](https://user-images.githubusercontent.com/20858804/27491038-585fba3e-585e-11e7-87cf-458676a299de.png)

**Comment by the-dagger** [comment]
@ArushiSinghal Could you try making these with #B62F69, #C02E64 and #753A88?
Thanks :)

**Comment by ArushiSinghal** [comment]
#753A88
![753a88_1](https://user-images.githubusercontent.com/20858804/27500780-a2cab802-5887-11e7-9841-fbd11ba45e88.png)
![753a88](https://user-images.githubusercontent.com/20858804/27500783-a62c0708-5887-11e7-9b9e-b8525b406ca3.png)
#C02E64
![c02e64](https://user-images.githubusercontent.com/20858804/27500798-b40c8410-5887-11e7-8c36-c2e67b6ed274.png)
![c02e64_1](https://user-images.githubusercontent.com/20858804/27500802-b6da7e22-5887-11e7-9344-1cda8a3acba5.png)
 #B62F69
![b62f69_1](https://user-images.githubusercontent.com/20858804/27500817-c0ae991a-5887-11e7-94e5-d6fbf397ef33.png)
![b62f69](https://user-images.githubusercontent.com/20858804/27500823-c430ca9a-5887-11e7-9756-759a16dc6632.png)

**Comment by abishekvashok** [comment]
#C02E64 lokks quite good @ArushiSinghal.

**Comment by ArushiSinghal** [comment]
@abishekvashok which one out of two is best a) or b).
And how should I send the pull request? Please guide.

**Comment by abishekvashok** [comment]
@ArushiSinghal `b`.
I am a student here.
Maybe some mentors like @the-dagger would have a final say on the icon.

**To add the icon**
Fork this repo, clone it.
Replace ic_launcher.png and ic_launcher_round.png files in the mipmap folder inside app/src/res/.
[_Note: there are various various dimensions_]
That would be enough as we are targeting Android `25`.

**Comment by ArushiSinghal** [comment]
@the-dagger please review.

**Comment by the-dagger** [comment]
@ArushiSinghal The last one looks good to me, but try avoiding the use of a gradient.
Also use #C02E64 for the bigger bubble and white for smaller one.
Without any gradient.

**Comment by ArushiSinghal** [comment]
@the-dagger Which one is fixed out of #C02E64 and #B62F69.
And which one out of two logos from each part.

**Comment by the-dagger** [comment]
Use this one. 
https://user-images.githubusercontent.com/20858804/27500823-c430ca9a-5887-11e7-9756-759a16dc6632.png 

Also for the bigger chat bubble, use #C02E64 and keep the smaller one while. 
The 3 dots in the smaller icon can also be made #C02E64

**Comment by ArushiSinghal** [comment]
**# #C02E64**
![imageedit_3_4628606602](https://user-images.githubusercontent.com/20858804/27526287-62f30efa-5a62-11e7-95e0-864f9b9a97a8.png)
 # **#B62F69**
![imageedit_5_5755261000](https://user-images.githubusercontent.com/20858804/27526299-6c43a5f0-5a62-11e7-9690-118db86d2029.png)

**Comment by ArushiSinghal** [comment]
@the-dagger Please Add Bounty to this issue.

**Comment by abishekvashok** [comment]
Should we reopen this @the-dagger
