### ISSUE TITLE
RoomFragment

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/Chatter#33]
RoomFragment is getting empty object 
![screen shot 2018-05-15 at 12 58 04 pm](https://user-images.githubusercontent.com/29139786/40042602-9fb8c77c-583f-11e8-8b84-a5e407b7436a.png)

**Comment by manav-mj** [comment]
RoomFragment is not showing messages due to a lot of bugs:
1. Gitter API endpoint used is to be updated to the new Gitter API.
2. Logic changes regarding the realm object

**Comment by manav-mj** [comment]
I suggest these bugs should also be included in the issue description
