### ISSUE TITLE
Enhance Dashboard Activity

### ISSUE THREAD

**Issue by abishekvashok** [coding-blocks/Chatter#4]
Populating the Dashboard Activity would be the next step to go forward.

- [ ] Store user data received from Gitter API, by making a call with access token to the API in shared Preferences.
- [ ] Implement Realm db
- [ ] If on the first use the user is offine it will redirect to NoNetwork Activity
- [ ] Get rooms data and store them in Realm db.
- [ ] Implement Recycler View in Dashboard Activity listing out the rooms and users with number of unread messages and sorted by last taken room time stamp from the Realm db.
- [ ] On clicking a room or user should open a  dedicated Activity. [Currently blank].

Difficulty: Hard

CC: @championswimmer @the-dagger 

Please add bounty points :)

**Comment by abishekvashok** [comment]
I am working on it. :)

**Comment by abishekvashok** [comment]
Done via #6.

**Comment by abishekvashok** [comment]
Pls add bounties @the-dagger @championswimmer

**Comment by the-dagger** [comment]
Thanks 🙂
