### ISSUE TITLE
New Icon For Chatter

### ISSUE THREAD

**Issue by chaostools** [coding-blocks/Chatter#40]
I think the App should have an icon  with chatter's Color palette  and gitter-like icon.
Working on it

**Comment by chaostools** [comment]
@the-dagger  please add some bounty on it :smile:

**Comment by aggarwalpulkit596** [comment]
@championswimmer fixed in #112

**Comment by venomousboxer** [comment]
@championswimmer can you please specify colour scheme required for the icon or can we design on our own.

**Comment by manav-mj** [comment]
I think we should agree upon the Design before submitting any PR

**My take on the logo:**

<img src="https://user-images.githubusercontent.com/22222147/41413157-da32786c-6fff-11e8-93ec-f30f6a78c80e.png" width="300px" height="300px"/>

**Comment by aggarwalpulkit596** [comment]
**My take on the logo:**

![2](https://user-images.githubusercontent.com/29139786/41422433-8a152dd6-7016-11e8-934e-f432e24e04ac.png)
![gitter-icon-cb-2](https://user-images.githubusercontent.com/29139786/41422435-8a413610-7016-11e8-957a-ea25503f5203.png)

**Comment by architkshk** [comment]
My take on the logo-

![](https://user-images.githubusercontent.com/5001704/41410310-b6c5272a-6ff6-11e8-9ea3-d8edd8a76337.png)

**Comment by venomousboxer** [comment]
**My take on the icons :**
![screen shot 2018-06-15 at 8 22 48 am](https://user-images.githubusercontent.com/31950172/41447917-6721125e-7075-11e8-9aaf-472ac8be09af.png)
![screen shot 2018-06-15 at 8 23 08 am](https://user-images.githubusercontent.com/31950172/41447918-6762f41c-7075-11e8-9b10-16fd2ea686bb.png)

**Comment by championswimmer** [comment]
I think we can simply use the Gitter official icon with a 'Unofficial' sticker on top right corner

**Comment by aggarwalpulkit596** [comment]
@championswimmer 
![6](https://user-images.githubusercontent.com/29139786/41463435-10488b1c-70b4-11e8-83d4-ae60394663f8.png)
will this work ?

**Comment by venomousboxer** [comment]
@aggarwalpulkit596 I think what @championswimmer means is that we need to add a sticker with text 'Unofficial' on top right corner.
@championswimmer bhaiya solved the issue in PR #115

**Comment by manav-mj** [comment]
<img src="https://user-images.githubusercontent.com/22222147/41465319-2c9fa17c-70bb-11e8-9d50-8e31e56ad83d.png" width="300px" height="300px"/>

**Comment by championswimmer** [comment]
@manav-mj this looks good
want to send this in as a PR ?

**Comment by championswimmer** [comment]
@manav-mj can you make the corner sticker slightly bigger? when on phone, it is kinda not legible. 
move the sticker 20% inwards, it'll allow you to make the font 10-15% bigger.

**Comment by manav-mj** [comment]
@championswimmer Submitted the PR 👍
