### ISSUE TITLE
Messages Not Populating

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/Chatter#90]
**Actual Behaviour**
Messages in message fragment not getting populated
**Expected Behaviour**

Messages should be populated according to the selected room

**Screenshots of the issue**

![screenshot-1527658077109](https://user-images.githubusercontent.com/29139786/40700769-9eef8b0e-63f8-11e8-8a80-f5afe5048ad9.jpg)

**Expected Bounty**

20

**Comment by RishabhRawatAndroid** [comment]
@aggarwalpulkit596  this is already done in the #89 PR with successful CI test.

**Comment by aggarwalpulkit596** [comment]
@RishabhRawatAndroid  what you have done is an improvisation and i have pointed out a bug so it's different
