### ISSUE TITLE
Swipe to refresh the RoomsFragment Layout

### ISSUE THREAD

**Issue by RishabhRawatAndroid** [coding-blocks/Chatter#91]
**Actual Behaviour**

Now there is no any option to refresh the RoomsFragment to know the unread message in RoomsFragment. We only have one option which is click the Room button in bottom navigation

**Expected Behaviour**

I think it is the good choice to refresh the RoomsFragment when we vertical swipe in the screen.

**Steps to reproduce it**

Adding theSwipeRefreshLayout in the RoomsFragment layout. 

**LogCat for the issue**

This is improvement

**Screenshots of the issue**
   No Screen shot 
**Expected Bounty**
  100
Mention the bounty you expect for the issue (if not tagged in the issue)

**Comment by aggarwalpulkit596** [comment]
no need to swipe refresh because the messages are coming in realtime like a socket
