### ISSUE TITLE
Adding Rxjava for Api calls

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/Chatter#93]
Use of Rx java and retrofit for API calls and checking networking connectivity in realtime using Rx java

**Comment by abishekvashok** [comment]
Why should we do that? We have okkayhhtp directly logged via Android studio

**Comment by aggarwalpulkit596** [comment]
Okhttp can work but rxjava is better way of implementing api call as well help in making asyn task calls in background

**Comment by abishekvashok** [comment]
You could wrap it around okkayhhtp, using retrofit seems like a bad option

**Comment by RishabhRawatAndroid** [comment]
The **Core** part of Chatter app is the Api calling and if you want to change the Okhttp from the retrofit and Rxjava then it will require a lot of changes in the source code.

**Comment by aggarwalpulkit596** [comment]
it will require a lot of changes but i guess it's worth it
