### ISSUE TITLE
No messages being displayed in the rooms

### ISSUE THREAD

**Issue by the-dagger** [coding-blocks/Chatter#95]
Current the messages are not being displayed in a room.
Also the networking is handled poorly, multiple API calls are made.

**Comment by aggarwalpulkit596** [comment]
On it

**Comment by aggarwalpulkit596** [comment]
in this,can i just display the messages in the room because poor API calls and rest of enhancement can be done in issue #98

**Comment by aggarwalpulkit596** [comment]
Fixed in #99

**Comment by RishabhRawatAndroid** [comment]
@the-dagger please see the #89 PR this issue resolve in this PR.

**Comment by aggarwalpulkit596** [comment]
@the-dagger bhaiya this issue has been fixed in #99 therefore it can be closed.
