### ISSUE TITLE
Materialize the app

### ISSUE THREAD

**Issue by the-dagger** [coding-blocks/Chatter#97]
The UI of the app is lacking in many aspects, this needs some tweaking.

Changes needed :
 
* Removing BottomNavigationBar and having 2 Activities, one for the rooms and other for messages.

* Getting rid of unnecessary activities and fragments

* Having a PreferenceActivity

**Comment by aggarwalpulkit596** [comment]
What is needed to be done in preferenceactivity ? @the-dagger
