### ISSUE TITLE
Restructure database

### ISSUE THREAD

**Issue by the-dagger** [coding-blocks/Chatter#98]
The current database schema is inefficient, we need to rewrite it from scratch (using room possibly).

This PR has 2 parts to it : 
Part 1 should aim to remove the database functionality from the app (for now) and use temporary variables to display all the data.

Part 2 should aim to implement a fresh database (using ROOM) with proper structuring.
I will be happy to help with this one.

**Comment by aggarwalpulkit596** [comment]
we need to remove all the use of realm and implement room instead of realm correct?

**Comment by the-dagger** [comment]
Yes, that is correct.

**Comment by aggarwalpulkit596** [comment]
@the-dagger i think this issue shouldn't be worked upon on until #97 issue has been completed.

**Comment by RishabhRawatAndroid** [comment]
@the-dagger I think every room should be its own Message table. This will solve the problem. Because at this time every room uses a single Message table So if we go to the different room then the previous room messages are displayed.

**Comment by aggarwalpulkit596** [comment]
Which can be easily fixed with a simple where clause in the query and no that is not the solution

**Comment by aggarwalpulkit596** [comment]
@the-dagger Bhaiya can help me out a bit I've created all the necessary classes and written queries in dao class but I need a little bit of your help

**Comment by aggarwalpulkit596** [comment]
@the-dagger bhaiya there is only one small error which is regarding UNIQUE constraint failed while updating somewhat simliar issue which was in #103 can you help me out in this one rest all is done

**Comment by aggarwalpulkit596** [comment]
@the-dagger  bhaiya i've updated the code on the github kindly help me out with few things.
Below is the link to github commit link
https://github.com/aggarwalpulkit596/Chatter/commit/6bfb91d481259c3bb435aa06a939c955ce45adb2

**Comment by the-dagger** [comment]
@aggarwalpulkit596 Sure, where are you stuck at?

**Comment by aggarwalpulkit596** [comment]
@the-dagger actually there is error for first the time selection of any room as for the first time the messagetable is empty for that particular selected room and i don't either know about proper structuring can you tell lit bit about it or maybe review my code if it's possible

**Comment by aggarwalpulkit596** [comment]
@the-dagger kindly review this pr
